import "../components/PolicyPage.css";
import CTASection from "../components/CTASection";
import PageHeader from "../components/PageHeader";
import { usePageTitle } from "../router";

export default function CookiePolicyPage() {
  usePageTitle("Cookie Policy");

  return (
    <>
      <PageHeader
        title="Cookie Policy"
        description="What we store in your browser, and why."
        ctaLabel="Contact Us"
        ctaPath="/contact"
      />

      <section className="section scam-alert">
        <div className="container scam-alert__container policy-page__container">
          <h2 className="scam-alert__heading">How do you like those cookies?</h2>
          <p>
            Cookies are small text files placed on your device when you visit a website. They are
            generated by a web page server and can be used by that server whenever the user visits
            the site.
          </p>

          <h2 className="scam-alert__heading">At Mspring Infotech India Pvt Ltd</h2>
          <p>
            We combine the power of today's technology with the expertise of our professionals to
            create an experience that is efficient, secure, and user-friendly. To achieve this
            goal, we use technology to our advantage, including cookies.
          </p>
          <p>
            Cookies help us provide a seamless browsing experience by recognizing you each time you
            visit the site and helping our team understand which parts of the website you find most
            interesting and useful.
          </p>
          <p>
            The cookie settings on this site are set to <strong>"allow all"</strong>, but you can
            change your settings at any time. Please keep in mind that if you do, you may lose some
            functionality.
          </p>
          <p>More information can be found in our Cookie Statement below.</p>

          <h2 className="scam-alert__heading">Cookie Statement</h2>
          <p>
            You are visiting{" "}
            <strong>
              <a href="http://www.mspringinfotech.com/" target="_blank" rel="noopener noreferrer">
                www.mspringinfotech.com
              </a>
            </strong>
            , the website of <strong>Mspring Infotech India Pvt Ltd</strong>, hereinafter referred
            to as <strong>"Mspring Infotech India Pvt Ltd"</strong>, <strong>"we"</strong>,{" "}
            <strong>"us"</strong>, or <strong>"our"</strong>.
          </p>
          <p>
            Our website (
            <strong>
              <a href="http://www.mspringinfotech.com/" target="_blank" rel="noopener noreferrer">
                www.mspringinfotech.com
              </a>
            </strong>
            ) and its subdomains use cookies.
          </p>
          <p>
            Cookies are small text files that are stored on your device (computer, tablet, or
            mobile phone) via your browser primarily to enhance the convenience of using the site,
            enable certain functions, and make visiting our website more efficient. Third parties
            may also place cookies and similar technologies to monitor your internet behavior and
            display personalized advertisements outside our website. The information stored in
            cookies relates to your device, browser, and the way you interact with our website. It
            is not linked to your name, address, or email address.
          </p>
          <p>
            To the extent that personal information is collected using cookies, such information
            will be processed only in accordance with our Privacy Policy.
          </p>

          <h2 className="scam-alert__heading">Which cookies do we use and why?</h2>
          <p>
            Cookies may be placed directly by our website or by trusted third parties with whom we
            work to help diagnose technical issues, analyze website traffic, understand visitor
            behavior, measure website performance, and identify user preferences.
          </p>

          <h3>Default Cookies</h3>
          <p>
            These cookies are essential to enable you to navigate the website and use its features,
            such as accessing secure areas of the website. Without these cookies, services you
            request, such as logging in, cannot be provided.
          </p>
          <p>
            Our website uses <strong>Google Analytics</strong>, provided by Google LLC, and{" "}
            <strong>Optimizely</strong>, provided by Optimizely Inc. These cookies help us
            understand how visitors use the website and enable us to improve user experience by
            testing different website features.
          </p>

          <h3>Functional Cookies</h3>
          <p>
            These cookies enable the website to provide enhanced functionality and personalization.
            They may be set by us or by trusted third-party providers whose services we have added
            to our pages. If you do not allow these cookies, some or all of these services may not
            function properly.
          </p>

          <h3>Performance Cookies</h3>
          <p>
            These cookies collect information about how visitors use our website, such as which
            pages are visited most often or whether users receive error messages. Only{" "}
            <strong>Mspring Infotech India Pvt Ltd</strong> has access to the data collected through
            these cookies, and we do not make this information available to third parties except
            where required to operate these services.
          </p>
          <p>
            Our website may use services such as <strong>Hotjar</strong> (provided by Hotjar Ltd.)
            and <strong>HubSpot</strong> (provided by HubSpot Inc.) to analyze website usage and
            improve user experience.
          </p>

          <h3>Advertising or Targeting Cookies</h3>
          <p>
            These cookies are used to deliver advertisements that are more relevant to your
            interests. They also help limit the number of times you see an advertisement and
            measure the effectiveness of advertising campaigns. These cookies are generally placed
            by advertising networks with our permission. They remember that you have visited our
            website, and this information may be shared with advertising partners or social media
            platforms that provide sharing functionality.
          </p>

          <h2 className="scam-alert__heading">Change Your Cookie Preferences</h2>
          <p>
            You can prevent your browser from storing cookies and/or delete cookies from your
            device at any time through your browser settings. Please refer to your browser's{" "}
            <strong>Help</strong> section for instructions.
          </p>
          <p>
            If you choose not to accept cookies, some features and functionality of our website may
            not be available, and certain sections of the website may not display correctly.
          </p>
          <p>
            To opt out of Google Analytics cookies, you can install the{" "}
            <strong>Google Analytics Opt-out Browser Add-on</strong>.
          </p>
          <p>To opt out of Optimizely cookies, you can visit the Optimizely opt-out page.</p>
          <p>
            To opt out of Hotjar cookies, you can visit the Hotjar opt-out page and select{" "}
            <strong>"Disable Hotjar."</strong>
          </p>

          <h2 className="scam-alert__heading">Storage Period</h2>
          <p>
            Most of the cookies we use are deleted when you close your browser session (session
            cookies). Other cookies remain stored on your device for up to <strong>2 years</strong>,
            except web analytics cookies, which may remain on your device for a maximum of{" "}
            <strong>10 years</strong>, depending on your browser settings and applicable
            regulations.
          </p>

          <h2 className="scam-alert__heading">Changes to the Cookie Statement</h2>
          <p>
            We may update this Cookie Statement from time to time. The latest revision date will be
            displayed at the bottom of this statement. We encourage you to review this Cookie
            Statement periodically to stay informed about how we use cookies.
          </p>
        </div>
      </section>

      <CTASection />
    </>
  );
}
